 export const purposeList = [
    "Job interview",
    "Internship interview",
    "Client meeting",
    "Project discussion",
    "Technical support",
    "Product demo",
    "Device pickup/drop-off",
    "Investor meeting",
    "Contract signing",
    "Training/workshop",
    "Research collaboration",
    "Vendor/supplier visit",
    "Staff onboarding",
    "Exit interview",
    "Background verification",
    "Maintenance/repair work",
    "Guest speaker session",
    "Hackathon/tech event",
    "Campus/company tour",
    "Legal/compliance meeting",
    "Other...",
  ];